book_shop(3)/auth_app/urls.py
from django.urls import path
import auth_app.views as authapp


app_name = 'auth_app'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.profile, name='profile'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

book_shop(3)/book_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import main, catalog, show_book_info, contacts, test


urlpatterns = [
    path('', main, name='main'),
    path('catalog/', include('mainapp.urls')),
    path('contacts/', contacts, name='contacts'),
    path('test/', test, name='test'),
    path('auth/', include('auth_app.urls', namespace='auth')),
    path('libr/', include('userlibrapp.urls', namespace='libr')),
    path('myadmin/', include('admin_app.urls', namespace='admin')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shop(3)/mainapp/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import catalog, show_book_info

urlpatterns = [
    path('', catalog, name='catalog'),
    path('<int:pk>/', catalog, name='catalog'),
    path('page/<int:num_page>/', catalog, name='page'),
    path('<int:pk>/page/<int:num_page>/', catalog, name='page'),
    path('book/<int:book_id>/', show_book_info, name='book'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shop(3)/auth_app/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta

# Create your models here.

class BookUser(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatar', verbose_name='Аватар', blank=True)
    age = models.PositiveIntegerField(verbose_name='Возраст')

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)))


    def is_key_expired(self):
        return True if now() <= self.activation_key_expires else False


    def __str__(self):
        return super().__str__()


    def user_count(self):
        """ Возвращает количество книг в библиотеке пользователя.  """

        return len(self.perslib.all())


class BookUserProfile(models.Model):
    MALE = 'm'
    FEMALE = 'w'

    gender_shoices = (
        (MALE, 'М'),
        (FEMALE, 'Ж')
    )

    user = models.OneToOneField(
        BookUser, 
        on_delete=CASCADE,
        null=False, 
        unique=True, 
        db_index=True
    )
    
    tagline = models.CharField(
        verbose_name='Теги',
        max_length=128,
        blank=True
    )

    about_me = models.TextField(verbose_name='О себе', max_length=32767, blank=True)
    gender = models.CharField(
        verbose_name='пол',
        max_length=1,
        choices=gender_shoices,
        blank=True
    )

    @receiver(post_save, sender=BookUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            BookUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=BookUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.bookuserprofile.save()

book_shop(3)/auth_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from django.db import models
from django.db.models import fields
from django.db.models.base import Model
from auth_app.models import BookUser, BookUserProfile
from random import random
from hashlib import sha1


class BookLoginUserForm(AuthenticationForm):
    class Meta:
        model = BookUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(BookLoginUserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BookUserEditForm(UserChangeForm):
    class Meta:
        model = BookUser
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'age', 'avatar']


    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class BookUserRegisterForm(UserCreationForm):
    class Meta:
        model = BookUser
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'age', 'avatar']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self):
        user = super(BookUserRegisterForm, self).save()
        user.is_active = False
        salt = sha1(str(random()).encode('utf-8')).hexdigest()[:6]
        user.activation_key = sha1((user.email + salt).encode('utf_8')).hexdigest()
        user.save()

        return user


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = BookUserProfile
        fields = ('tagline', 'gender', 'about_me')

book_shop(3)/auth_app/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from auth_app.models import BookUser, BookUserProfile
from auth_app.forms import BookLoginUserForm, BookUserEditForm, BookUserRegisterForm, EditProfileForm
from userlibrapp.models import PersonLib
from django.db import transaction


# Create your views here.


def login(request):
    """ Страница авторизации.  """

    title = 'Вход'
    login_form = BookLoginUserForm(data=request.POST)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {
        'title': title,
        'login_form':login_form,
    }

    return render(request, 'auth_app/login.html', context=content)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('auth:login'))


@login_required
def profile(request):
    """ Просмотр профиля аутентифицированного пользователя. """

    title = 'Профиль пользователя'

    context = {
        'title':title,
    }

    return render(request, 'auth_app/profile_view.html', context=context)


@login_required
@transaction.atomic
def edit(request):
    """ Редактирование профиля пользователя.  """

    title = 'Изменить профиль пользователя'

    if request.method == 'POST':
        edit_form = BookUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.bookuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:profile'))
    else:
        edit_form = BookUserEditForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.bookuserprofile)

    context = {
        'title':title,
        'form': edit_form,
        'id_view':'edit',
        'pform': profile_form,
    }

    return render(request, 'auth_app/profile_editor.html', context=context)


def send_verify_mail(user):
    """ Отправляет регистрирующемуся  пользователю E-Mail с кодом подтверждения регистрации.  """

    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])
    title = f'Подтверждение учётной записи пользователя {user.username}.'
    message = f'Для подтверждения учётной записи {user.username} на портале {settings.DOMAIN_NAME} перейдите по ссылке\n{settings.DOMAIN_NAME}{verify_link}'

    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def register(request):
    """ Регистрация нового пользователя """

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('auth:profile')) # Аутентифицированным пользователям здесь делать нечего.

    title = 'Регистрация нового пользователя'
    
    if request.method == 'POST':
        reg_form = BookUserRegisterForm(request.POST, request.FILES)
        if reg_form.is_valid():
            new_user = reg_form.save()
            if send_verify_mail(new_user):
                auth.login(request, new_user)
                return HttpResponseRedirect(reverse('auth:login'))
            else:
                print('Ошибка отправки сообщения!')
                return HttpResponseRedirect(reverse('auth:login'))
    else:
        reg_form = BookUserRegisterForm

    context = {
        'title':title,
        'form':reg_form,
        'id_view':'registr', # Чтобы отличить форму для регистрации от формы для редактирования пользователя.
        'user_count': None,
    }

    return render(request, 'auth_app/profile_editor.html', context)


def verify(request, email, activation_key):
    """ Верификация пользователя. """

    try:
        user = get_object_or_404(BookUser, email=email)

        if user.activation_key == activation_key and user.is_key_expired():
            user.is_active = True
            user.activation_key = ''
            user.save()
            auth.login(request, user)
            return render(request, 'auth_app/verification.html')
        else:
            print(f'Ошибка верификации пользователя {user}')
            return render(request, 'auth_app/verification.html')
    except Exception as e:
        print(f'Ошибка активации пользователя {user.username}: {e.args}')
        return HttpResponseRedirect(reverse('main'))

book_shop(3)/auth_app/templates/auth_app/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>Введите данные для входа:</h1>
<form action="{% url 'auth:login' %}" method="POST">
    {% csrf_token %}
    {{ login_form.as_p }}
    <br>
    <input type="submit", value="Войти!">
</form>
<div><a href="{% url 'social:begin' 'facebook' %}">Вход через Facebook</a></div>
{% endblock %}

book_shop(3)/auth_app/templates/auth_app/profile_editor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }} {{ user.username }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ title }} {{ user.username }}</h1>

<form action="
{% if id_view == 'registr' %}
{% url 'auth:register' %}
{% endif %}
{% if id_view == 'edit' %}
{% url 'auth:edit' %}
{% endif %}
" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if pform %}{{ pform.as_p }}{% endif %}
    <input type="submit" 
    {% if id_view == 'edit' %}
        value="Сохранить"
        {% endif %}
        {% if id_view == 'registr' %}
        value="Зарегистрироваться"
        {% endif %}
        >
</form>
{% endblock %}

book_shop(3)/auth_app/templates/auth_app/profile_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }} - {{ user.first_name|default:user.username }} {{ user.last_name|default:'' }} - {{ block.super }}
{% endblock %}}

{% block main %}
<h1>Профиль пользователя {{ user.username }}</h1>
<ul>
    <li><strong>Пользователь:</strong> {{user.username }}</li>
    <li><strong>Email:</strong> {{ user.email|default:'Не задан' }}</li>
    <li><strong>Имя:</strong> {{ user.first_name|default:'Не задан' }}</li>
    <li><strong>Фамилия:</strong> {{ user.last_name|default:'Не задан' }}</li>
    <li><strong>Возраст:</strong> {{ user.age|default:'Не задан' }}</li>
    <li><img src="{{ user.avatar }}" alt="Аватарка"></li>
    <li><strong>Теги: </strong>{{ user.bookuserprofile.tigline|default:'Не заданы' }}</li>
    <li><strong>Пол: </strong>{{ user.bookuserprofile.gender|default:'Не указан' }}</li>
    <li><strong>О себе:</strong> {{ user.bookuserprofile.about_me }}</li>
</ul>
<p><a href="{% url 'auth:edit' %}">Изменить.</a></p>
{% if not user.is_active %}
<p>Вы не активировали свой аккаунт. <a href="{% url 'auth:verify' user.email user.activation_key %}">Отправить активационное письмо?</a></p>
{% endif %}
{% endblock %}

book_shop(3)/auth_app/templates/auth_app/verification.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Верификация пользователя {% if user %}{{ user.username }}{% endif %}
{% endblock %}

{% block main %}
{% if not user.is_anonymous %}
<h1>Поздравляем!</h1>
<p>Пользователь {{ user.username }} подтверждён.</p>
<p><a href="{% url 'auth:profile' %}">Перейти в профиль</a></p>
{% else %}
<h1>Сожалеем.</h1>
<p>Подтверждение пользователя не произошло.</p>
<p><a href="{% url 'main' %}">На главную</a></p>
{% endif %}
{% endblock %}