hw4_dukhonin/auth_app/urls.py
import auth_app
from django.urls import path
from django.urls.resolvers import URLPattern
import auth_app.views as     authapp

app_name = 'auth_app'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/<str:action>/', authapp.profile, name='profile'),
]

hw4_dukhonin/auth_app/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.db.models import fields
from .models import BookUser
from auth_app import models

class BookLoginUserForm(AuthenticationForm):
    class Meta:
        model = BookUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(BookLoginUserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BookUserEditForm(UserChangeForm):
    class Meta:
        model = BookUser
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'age', 'avatar']
    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            # if field_name == 'password':
                # field.widget = forms.HittenInput()

hw4_dukhonin/auth_app/views.py
from django import http
from django.http import request
from django.shortcuts import render, HttpResponseRedirect
from auth_app.forms import BookLoginUserForm, BookUserEditForm
from django.contrib import auth
from django.urls import reverse

# Create your views here.

def login(request):
    title = 'Вход'
    login_form = BookLoginUserForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))
    content = {'title': title, 'login_form':login_form}
    return render(request, 'auth_app/login.html', context=content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def profile(request, action='view'):
    title = 'Профиль'

    if request.user.is_anonymous:
        return HttpResponseRedirect(reverse('main'))

    if action == 'edit':
        title = 'редактирование профиля пользователя'
        if request.method == 'POST':
            edit_form = BookUserEditForm(request.POST, request.FILES, instance=request.user)
            if edit_form.is_valid():
                edit_form.save()
                return render(request, 'auth_app/profile_view.html', {'title':'профиль пользователя'})
        else:
            edit_form = BookUserEditForm(instance=request.user)
        return render(request, 'auth_app/profile_editor.html', context={'title':title, 'edit_form':edit_form})
    return render(request, 'auth_app/profile_view.html', {'title':title})

hw4_dukhonin/auth_app/templates/auth_app/profile_editor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }} {{ user.username }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ title }} {{ user.username }}</h1>

<form action="{% url 'auth:profile' 'edit' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

hw4_dukhonin/auth_app/templates/auth_app/profile_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }} - {{ user.first_name|default:user.username }} {{ user.last_name|default:'' }} - {{ block.super }}
{% endblock %}}

{% block main %}
<h1>Профиль пользователя {{ user.username }}</h1>
<ul>
    <li><strong>Пользователь:</strong> {{user.username }}</li>
    <li><strong>Email:</strong> {{ user.email|default:'Не задан' }}</li>
    <li><strong>Имя:</strong> {{ user.first_name|default:'Не задан' }}</li>
    <li><strong>Фамилия:</strong> {{ user.last_name|default:'Не задан' }}</li>
    <li><strong>Возраст:</strong> {{ user.age|default:'Не задан' }}</li>
    <li><img src="{{ user.avatar }}" alt="Аватарка"></li>
</ul>
<p><a href="{% url 'auth:profile' 'edit' %}">Изменить.</a></p>
{% endblock %}